### ISSUE TITLE
Issue Archiving

### ISSUE THREAD

**Issue by xonmin** [mash-up-kr/MOIT-backend#1]

**Comment by xonmin** [comment]
노션으로 대체

**Comment by KimDoubleB** [comment]
![appicon2](https://github.com/mash-up-kr/MOIT-backend/assets/37873745/90d91e84-8cb0-4955-b356-1b39ee3c14fd)

<img width="1024" alt="appicon" src="https://github.com/mash-up-kr/MOIT-backend/assets/37873745/f05eb6dc-fecd-4f32-8b41-ae9cb86b430b">

**Comment by KimDoubleB** [comment]
<img width="297" alt="image" src="https://github.com/mash-up-kr/MOIT-backend/assets/37873745/d208f330-48cb-46d8-a971-b00a4dcfa87a">

**Comment by hope1053** [comment]
![kakaotalk](https://github.com/mash-up-kr/MOIT-backend/assets/22907483/020852b8-ffc7-472c-bd1b-6debf5aa8cab)

**Comment by KimDoubleB** [comment]
![image](https://github.com/mash-up-kr/MOIT-backend/assets/37873745/7c9b977f-6fc5-4fc0-8be9-a21ffd93c07c)
